-- ANVI Clothing — catalog seed v1 (idempotent). Paste into SQL Editor and Run.
-- Source: src/data/products.ts + src/data/categories.ts

-- ---------- categories ----------
insert into public.categories (legacy_id, name, slug, short_description, image_url, featured, display_order, is_active) values ('cat-sarees', 'Sarees', 'sarees', 'Heritage weaves & celebratory silk drapes.', '/images/categories/sarees.jpg', TRUE, 1, TRUE) on conflict (slug) do update set name=excluded.name, short_description=excluded.short_description, image_url=excluded.image_url, featured=excluded.featured, display_order=excluded.display_order, is_active=TRUE;
insert into public.categories (legacy_id, name, slug, short_description, image_url, featured, display_order, is_active) values ('cat-salwars', 'Salwars', 'salwars', 'Effortless kalidars & everyday elegance.', '/images/categories/salwars.jpg', FALSE, 2, TRUE) on conflict (slug) do update set name=excluded.name, short_description=excluded.short_description, image_url=excluded.image_url, featured=excluded.featured, display_order=excluded.display_order, is_active=TRUE;
insert into public.categories (legacy_id, name, slug, short_description, image_url, featured, display_order, is_active) values ('cat-coords', 'Co-ord Sets', 'co-ord-sets', 'Modern artisanal block-printed pairings.', '/images/categories/coords.jpg', FALSE, 3, TRUE) on conflict (slug) do update set name=excluded.name, short_description=excluded.short_description, image_url=excluded.image_url, featured=excluded.featured, display_order=excluded.display_order, is_active=TRUE;
insert into public.categories (legacy_id, name, slug, short_description, image_url, featured, display_order, is_active) values ('cat-3piece', '3-Piece Sets', '3-piece-sets', 'Zardozi-embroidered festive ensembles.', '/images/categories/three_piece.jpg', FALSE, 4, TRUE) on conflict (slug) do update set name=excluded.name, short_description=excluded.short_description, image_url=excluded.image_url, featured=excluded.featured, display_order=excluded.display_order, is_active=TRUE;
insert into public.categories (legacy_id, name, slug, short_description, image_url, featured, display_order, is_active) values ('cat-kidswear', 'Kidswear', 'kidswear', 'Handcrafted zari pattu pavadai miniatures.', '/images/categories/kidswear.jpg', FALSE, 5, TRUE) on conflict (slug) do update set name=excluded.name, short_description=excluded.short_description, image_url=excluded.image_url, featured=excluded.featured, display_order=excluded.display_order, is_active=TRUE;

-- ---------- collections ----------
insert into public.collections (name, slug, is_active) values ('New Arrivals', 'new-arrivals', TRUE) on conflict (slug) do nothing;
insert into public.collections (name, slug, is_active) values ('Premium', 'premium', TRUE) on conflict (slug) do nothing;
insert into public.collections (name, slug, is_active) values ('The ANVI Edit', 'the-anvi-edit', TRUE) on conflict (slug) do nothing;
insert into public.collections (name, slug, is_active) values ('Bestsellers', 'bestsellers', TRUE) on conflict (slug) do nothing;
insert into public.collections (name, slug, is_active) values ('Festive Edit', 'festive-edit', TRUE) on conflict (slug) do nothing;

-- ---------- occasions ----------
insert into public.occasions (name, slug, is_active) values ('Everyday', 'everyday', TRUE) on conflict (slug) do nothing;
insert into public.occasions (name, slug, is_active) values ('Office', 'office', TRUE) on conflict (slug) do nothing;
insert into public.occasions (name, slug, is_active) values ('Festive', 'festive', TRUE) on conflict (slug) do nothing;

-- ---------- products + images + variants + inventory + tags + junctions ----------
-- ajrakh-chanderi-silk-saree
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-01', 'ANV-001', 'Ajrakh Chanderi Silk Saree', 'ajrakh-chanderi-silk-saree', (select id from public.categories where slug='sarees'), 'Sarees', 'Handwoven pure Chanderi silk saree featuring intricate natural dye Ajrakh handblock motifs with woven zari border and zari pallu.', 4850, 5600, 'Limited Pieces', TRUE, TRUE, TRUE, TRUE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='ajrakh-chanderi-silk-saree');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='ajrakh-chanderi-silk-saree'), '/images/products/saree_ajrakh_1.jpg', TRUE, 0), ((select id from public.products where slug='ajrakh-chanderi-silk-saree'), '/images/products/saree_ajrakh_2.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='ajrakh-chanderi-silk-saree');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='ajrakh-chanderi-silk-saree'), 'Free Size', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='ajrakh-chanderi-silk-saree');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='ajrakh-chanderi-silk-saree';
delete from public.product_tags where product_id=(select id from public.products where slug='ajrakh-chanderi-silk-saree');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='ajrakh-chanderi-silk-saree'), 'Handloom'), ((select id from public.products where slug='ajrakh-chanderi-silk-saree'), 'Ajrakh'), ((select id from public.products where slug='ajrakh-chanderi-silk-saree'), 'Pure Silk');
delete from public.product_collections where product_id=(select id from public.products where slug='ajrakh-chanderi-silk-saree');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='ajrakh-chanderi-silk-saree'), id from public.collections where slug='new-arrivals';
delete from public.product_occasions where product_id=(select id from public.products where slug='ajrakh-chanderi-silk-saree');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='ajrakh-chanderi-silk-saree'), id from public.occasions where slug='festive';

-- taamara-madder-red-bagru-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-02', 'ANV-002', 'Taamara Madder Red Bagru Set', 'taamara-madder-red-bagru-set', (select id from public.categories where slug='salwars'), 'Salwars', 'Flared Kalidar Anarkali silhouette in natural Madder Red Bagru handblock print, paired with tailored cotton trousers and a sheer Chanderi dupatta.', 3450, NULL, 'In Stock', TRUE, TRUE, TRUE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='taamara-madder-red-bagru-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='taamara-madder-red-bagru-set'), '/images/products/salwar_bagru_1.jpg', TRUE, 0), ((select id from public.products where slug='taamara-madder-red-bagru-set'), '/images/products/salwar_bagru_2.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='taamara-madder-red-bagru-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'S', TRUE), ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'M', TRUE), ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'L', TRUE), ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'XL', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='taamara-madder-red-bagru-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='taamara-madder-red-bagru-set';
delete from public.product_tags where product_id=(select id from public.products where slug='taamara-madder-red-bagru-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'Bagru'), ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'Handblock'), ((select id from public.products where slug='taamara-madder-red-bagru-set'), 'Cotton');
delete from public.product_collections where product_id=(select id from public.products where slug='taamara-madder-red-bagru-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='taamara-madder-red-bagru-set'), id from public.collections where slug='new-arrivals';
delete from public.product_occasions where product_id=(select id from public.products where slug='taamara-madder-red-bagru-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='taamara-madder-red-bagru-set'), id from public.occasions where slug='everyday';

-- indigo-kalamkari-co-ord-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-03', 'ANV-003', 'Indigo Kalamkari Co-ord Set', 'indigo-kalamkari-co-ord-set', (select id from public.categories where slug='co-ord-sets'), 'Co-ord Sets', 'Contemporary two-piece ethnic co-ord set in fermented organic indigo dye with botanical block-printed motifs and tailored comfort-fit trousers.', 2850, NULL, 'In Stock', TRUE, TRUE, TRUE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='indigo-kalamkari-co-ord-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), '/images/products/coord_indigo_1.jpg', TRUE, 0), ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), '/images/products/coord_indigo_2.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='indigo-kalamkari-co-ord-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'XS', TRUE), ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'S', TRUE), ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'M', TRUE), ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'L', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='indigo-kalamkari-co-ord-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='indigo-kalamkari-co-ord-set';
delete from public.product_tags where product_id=(select id from public.products where slug='indigo-kalamkari-co-ord-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'Indigo'), ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'Co-ord'), ((select id from public.products where slug='indigo-kalamkari-co-ord-set'), 'Workwear');
delete from public.product_collections where product_id=(select id from public.products where slug='indigo-kalamkari-co-ord-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='indigo-kalamkari-co-ord-set'), id from public.collections where slug='new-arrivals';
delete from public.product_occasions where product_id=(select id from public.products where slug='indigo-kalamkari-co-ord-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='indigo-kalamkari-co-ord-set'), id from public.occasions where slug='office';

-- ivory-zardozi-chanderi-3-piece-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-04', 'ANV-004', 'Ivory Zardozi Chanderi 3-Piece Set', 'ivory-zardozi-chanderi-3-piece-set', (select id from public.categories where slug='3-piece-sets'), '3-Piece Sets', 'Ethereal ivory raw silk & Chanderi 3-piece set detailed with delicate hand-embroidered zardozi neckline and scalloped sheer organza dupatta.', 5400, NULL, 'Limited Pieces', TRUE, TRUE, TRUE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), '/images/products/set_ivory_1.jpg', TRUE, 0), ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), '/images/products/set_ivory_2.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), 'S', TRUE), ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), 'M', TRUE), ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), 'L', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='ivory-zardozi-chanderi-3-piece-set';
delete from public.product_tags where product_id=(select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), 'Zardozi'), ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), 'Festive'), ((select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), 'Organza');
delete from public.product_collections where product_id=(select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), id from public.collections where slug='premium';
delete from public.product_occasions where product_id=(select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='ivory-zardozi-chanderi-3-piece-set'), id from public.occasions where slug='festive';

-- kanjeevaram-antique-zari-silk-saree
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-05', 'ANV-005', 'Kanjeevaram Antique Zari Saree', 'kanjeevaram-antique-zari-silk-saree', (select id from public.categories where slug='sarees'), 'Sarees', 'Regal heirloom handwoven mulberry silk Kanjeevaram saree accented with pure gold and silver dipped antique zari korvai borders.', 12500, 14000, 'Limited Pieces', TRUE, FALSE, FALSE, TRUE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='kanjeevaram-antique-zari-silk-saree');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), '/images/occasions/occasion_festive.jpg', TRUE, 0), ((select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), '/images/campaigns/festive_campaign_detail.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='kanjeevaram-antique-zari-silk-saree');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), 'Free Size', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='kanjeevaram-antique-zari-silk-saree');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='kanjeevaram-antique-zari-silk-saree';
delete from public.product_tags where product_id=(select id from public.products where slug='kanjeevaram-antique-zari-silk-saree');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), 'Kanjeevaram'), ((select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), 'Heirloom'), ((select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), 'Zari');
delete from public.product_collections where product_id=(select id from public.products where slug='kanjeevaram-antique-zari-silk-saree');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), id from public.collections where slug='premium';
delete from public.product_occasions where product_id=(select id from public.products where slug='kanjeevaram-antique-zari-silk-saree');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='kanjeevaram-antique-zari-silk-saree'), id from public.occasions where slug='festive';

-- dusty-rose-linen-workwear-co-ord
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-06', 'ANV-006', 'Dusty Rose Linen Workwear Co-ord', 'dusty-rose-linen-workwear-co-ord', (select id from public.categories where slug='co-ord-sets'), 'Co-ord Sets', 'Minimalist breathable French flax linen tunic with architectural seam detailing and cropped straight-leg cigarette trousers.', 3200, NULL, 'In Stock', TRUE, FALSE, FALSE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='dusty-rose-linen-workwear-co-ord');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), '/images/occasions/occasion_office.jpg', TRUE, 0), ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), '/images/categories/coords.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='dusty-rose-linen-workwear-co-ord');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'S', TRUE), ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'M', TRUE), ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'L', TRUE), ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'XL', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='dusty-rose-linen-workwear-co-ord');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='dusty-rose-linen-workwear-co-ord';
delete from public.product_tags where product_id=(select id from public.products where slug='dusty-rose-linen-workwear-co-ord');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'Linen'), ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'Minimal'), ((select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), 'Office');
delete from public.product_collections where product_id=(select id from public.products where slug='dusty-rose-linen-workwear-co-ord');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), id from public.collections where slug='the-anvi-edit';
delete from public.product_occasions where product_id=(select id from public.products where slug='dusty-rose-linen-workwear-co-ord');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='dusty-rose-linen-workwear-co-ord'), id from public.occasions where slug='office';

-- meenakar-handloom-mulmul-salwar-suit
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-07', 'ANV-007', 'Meenakar Handloom Mulmul Salwar', 'meenakar-handloom-mulmul-salwar-suit', (select id from public.categories where slug='salwars'), 'Salwars', 'Featherlight 100% fine count mulmul kurta set with pastel hand-painted floral meenakari yoke and scalloped lace hemline.', 2950, NULL, 'In Stock', TRUE, FALSE, TRUE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), '/images/occasions/occasion_everyday.jpg', TRUE, 0), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), '/images/categories/salwars.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'XS', TRUE), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'S', TRUE), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'M', TRUE), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'L', TRUE), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'XL', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='meenakar-handloom-mulmul-salwar-suit';
delete from public.product_tags where product_id=(select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'Mulmul'), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'Breathable'), ((select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), 'Summer');
delete from public.product_collections where product_id=(select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), id from public.collections where slug='bestsellers';
delete from public.product_occasions where product_id=(select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='meenakar-handloom-mulmul-salwar-suit'), id from public.occasions where slug='everyday';

-- chandrakala-crimson-zari-anarkali-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-08', 'ANV-008', 'Chandrakala Crimson Anarkali Set', 'chandrakala-crimson-zari-anarkali-set', (select id from public.categories where slug='3-piece-sets'), '3-Piece Sets', 'Floor-length flared raw silk Anarkali in royal crimson ruby, highlighted with hand-beaded gota patti and matching churidar.', 7800, 8900, 'Limited Pieces', TRUE, FALSE, FALSE, TRUE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='chandrakala-crimson-zari-anarkali-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), '/images/occasions/occasion_premium.jpg', TRUE, 0), ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), '/images/categories/three_piece.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='chandrakala-crimson-zari-anarkali-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), 'S', TRUE), ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), 'M', TRUE), ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), 'L', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='chandrakala-crimson-zari-anarkali-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='chandrakala-crimson-zari-anarkali-set';
delete from public.product_tags where product_id=(select id from public.products where slug='chandrakala-crimson-zari-anarkali-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), 'Gota Patti'), ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), 'Silk'), ((select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), 'Couture');
delete from public.product_collections where product_id=(select id from public.products where slug='chandrakala-crimson-zari-anarkali-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), id from public.collections where slug='premium';
delete from public.product_occasions where product_id=(select id from public.products where slug='chandrakala-crimson-zari-anarkali-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='chandrakala-crimson-zari-anarkali-set'), id from public.occasions where slug='festive';

-- aadya-little-festive-pattu-pavada-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-09', 'ANV-009', 'Aadya Festive Pattu Pavada Set', 'aadya-little-festive-pattu-pavada-set', (select id from public.categories where slug='kidswear'), 'Kidswear', 'Traditional South Indian pure silk brocade lehenga and blouse tailored with soft organic cotton inner lining for sensitive skin.', 2400, NULL, 'In Stock', TRUE, FALSE, FALSE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='aadya-little-festive-pattu-pavada-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), '/images/categories/kidswear.jpg', TRUE, 0);
delete from public.product_variants where product_id=(select id from public.products where slug='aadya-little-festive-pattu-pavada-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), '2-3Y', TRUE), ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), '4-5Y', TRUE), ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), '6-7Y', TRUE), ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), '8-9Y', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='aadya-little-festive-pattu-pavada-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='aadya-little-festive-pattu-pavada-set';
delete from public.product_tags where product_id=(select id from public.products where slug='aadya-little-festive-pattu-pavada-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), 'Kidswear'), ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), 'Pattu Pavada'), ((select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), 'Traditional');
delete from public.product_collections where product_id=(select id from public.products where slug='aadya-little-festive-pattu-pavada-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), id from public.collections where slug='festive-edit';
delete from public.product_occasions where product_id=(select id from public.products where slug='aadya-little-festive-pattu-pavada-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='aadya-little-festive-pattu-pavada-set'), id from public.occasions where slug='festive';

-- marigold-yellow-tussar-georgette-saree
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-10', 'ANV-010', 'Marigold Tussar Georgette Saree', 'marigold-yellow-tussar-georgette-saree', (select id from public.categories where slug='sarees'), 'Sarees', 'Textured wild Tussar georgette drape in auspicious festive marigold yellow, with woven temple border and contrasting raw silk blouse piece.', 6200, NULL, 'In Stock', TRUE, FALSE, TRUE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='marigold-yellow-tussar-georgette-saree');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), '/images/categories/sarees.jpg', TRUE, 0), ((select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), '/images/products/saree_ajrakh_2.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='marigold-yellow-tussar-georgette-saree');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), 'Free Size', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='marigold-yellow-tussar-georgette-saree');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='marigold-yellow-tussar-georgette-saree';
delete from public.product_tags where product_id=(select id from public.products where slug='marigold-yellow-tussar-georgette-saree');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), 'Tussar'), ((select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), 'Handwoven'), ((select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), 'Festive');
delete from public.product_collections where product_id=(select id from public.products where slug='marigold-yellow-tussar-georgette-saree');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), id from public.collections where slug='bestsellers';
delete from public.product_occasions where product_id=(select id from public.products where slug='marigold-yellow-tussar-georgette-saree');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='marigold-yellow-tussar-georgette-saree'), id from public.occasions where slug='festive';

-- sage-mint-sheer-organza-saree
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-11', 'ANV-011', 'Sage Mint Sheer Organza Saree', 'sage-mint-sheer-organza-saree', (select id from public.categories where slug='sarees'), 'Sarees', 'Weightless semi-sheer sage mint glass organza drape hand-embellished with subtle sequin clusters and delicate scalloped embroidery.', 5900, NULL, 'In Stock', TRUE, TRUE, FALSE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='sage-mint-sheer-organza-saree');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='sage-mint-sheer-organza-saree'), '/images/hero/hero_desktop.jpg', TRUE, 0), ((select id from public.products where slug='sage-mint-sheer-organza-saree'), '/images/hero/anvi_editorial_hero_1788956439054.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='sage-mint-sheer-organza-saree');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='sage-mint-sheer-organza-saree'), 'Free Size', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='sage-mint-sheer-organza-saree');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='sage-mint-sheer-organza-saree';
delete from public.product_tags where product_id=(select id from public.products where slug='sage-mint-sheer-organza-saree');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='sage-mint-sheer-organza-saree'), 'Organza'), ((select id from public.products where slug='sage-mint-sheer-organza-saree'), 'Pastel'), ((select id from public.products where slug='sage-mint-sheer-organza-saree'), 'Celebratory');
delete from public.product_collections where product_id=(select id from public.products where slug='sage-mint-sheer-organza-saree');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='sage-mint-sheer-organza-saree'), id from public.collections where slug='the-anvi-edit';
delete from public.product_occasions where product_id=(select id from public.products where slug='sage-mint-sheer-organza-saree');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='sage-mint-sheer-organza-saree'), id from public.occasions where slug='festive';

-- charcoal-black-chanderi-tunic-trouser-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-12', 'ANV-012', 'Charcoal Black Chanderi Tunic Set', 'charcoal-black-chanderi-tunic-trouser-set', (select id from public.categories where slug='co-ord-sets'), 'Co-ord Sets', 'Structured high-low tunic in deep charcoal Chanderi with side pocket inserts, matched with cropped ankle-slit cigarette pants.', 3600, NULL, 'In Stock', TRUE, FALSE, FALSE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), '/images/campaigns/everyday_elevated.jpg', TRUE, 0), ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), '/images/products/coord_indigo_2.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'S', TRUE), ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'M', TRUE), ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'L', TRUE), ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'XL', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='charcoal-black-chanderi-tunic-trouser-set';
delete from public.product_tags where product_id=(select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'Contemporary'), ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'Chanderi'), ((select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), 'Office');
delete from public.product_collections where product_id=(select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), id from public.collections where slug='the-anvi-edit';
delete from public.product_occasions where product_id=(select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='charcoal-black-chanderi-tunic-trouser-set'), id from public.occasions where slug='office';

-- amrapali-gulab-angrakha-salwar-suit
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-13', 'ANV-013', 'Amrapali Gulab Angrakha Suit', 'amrapali-gulab-angrakha-salwar-suit', (select id from public.categories where slug='salwars'), 'Salwars', 'Cross-over Angrakha kurta in rose-tinted Chanderi with handcrafted latkans and matching printed Kota Doria dupatta.', 4200, NULL, 'In Stock', TRUE, FALSE, FALSE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), '/images/products/salwar_bagru_2.jpg', TRUE, 0), ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), '/images/products/salwar_bagru_1.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), 'S', TRUE), ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), 'M', TRUE), ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), 'L', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='amrapali-gulab-angrakha-salwar-suit';
delete from public.product_tags where product_id=(select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), 'Angrakha'), ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), 'Handcraft'), ((select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), 'Pastel');
delete from public.product_collections where product_id=(select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), id from public.collections where slug='new-arrivals';
delete from public.product_occasions where product_id=(select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='amrapali-gulab-angrakha-salwar-suit'), id from public.occasions where slug='everyday';

-- tarini-junior-floral-kurta-pyjama-set
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-14', 'ANV-014', 'Tarini Junior Floral Kurta Set', 'tarini-junior-floral-kurta-pyjama-set', (select id from public.categories where slug='kidswear'), 'Kidswear', 'Soft organic cotton handblock printed kurta paired with elasticated dhoti pants, ideal for festival morning pujas.', 1850, NULL, 'In Stock', TRUE, FALSE, FALSE, FALSE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), '/images/categories/kidswear.jpg', TRUE, 0);
delete from public.product_variants where product_id=(select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), '1-2Y', TRUE), ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), '3-4Y', TRUE), ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), '5-6Y', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='tarini-junior-floral-kurta-pyjama-set';
delete from public.product_tags where product_id=(select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), 'Kidswear'), ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), 'Cotton'), ((select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), 'Everyday');
delete from public.product_collections where product_id=(select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), id from public.collections where slug='the-anvi-edit';
delete from public.product_occasions where product_id=(select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='tarini-junior-floral-kurta-pyjama-set'), id from public.occasions where slug='everyday';

-- shikargah-banarasi-tissue-silk-saree
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-15', 'ANV-015', 'Shikargah Banarasi Tissue Saree', 'shikargah-banarasi-tissue-silk-saree', (select id from public.categories where slug='sarees'), 'Sarees', 'Museum-grade handwoven Banarasi tissue silk with intricate Shikargah flora and fauna motifs rendered in antique silver and gold zari.', 16800, 19500, 'Limited Pieces', TRUE, FALSE, FALSE, TRUE, FALSE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='shikargah-banarasi-tissue-silk-saree');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), '/images/campaigns/festive_campaign_main.jpg', TRUE, 0), ((select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), '/images/campaigns/festive_campaign_detail.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='shikargah-banarasi-tissue-silk-saree');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), 'Free Size', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='shikargah-banarasi-tissue-silk-saree');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='shikargah-banarasi-tissue-silk-saree';
delete from public.product_tags where product_id=(select id from public.products where slug='shikargah-banarasi-tissue-silk-saree');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), 'Banarasi'), ((select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), 'Tissue Silk'), ((select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), 'Heirloom');
delete from public.product_collections where product_id=(select id from public.products where slug='shikargah-banarasi-tissue-silk-saree');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), id from public.collections where slug='premium';
delete from public.product_occasions where product_id=(select id from public.products where slug='shikargah-banarasi-tissue-silk-saree');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='shikargah-banarasi-tissue-silk-saree'), id from public.occasions where slug='festive';

-- neelam-azure-chanderi-3-piece-sharara
insert into public.products (legacy_id, sku, name, slug, category_id, category, description, price_int, original_price_int, availability, is_active, is_new_arrival, is_bestseller, is_on_sale, is_out_of_stock, fabric, fabric_care) values ('prod-16', 'ANV-016', 'Neelam Azure Chanderi Sharara', 'neelam-azure-chanderi-3-piece-sharara', (select id from public.categories where slug='3-piece-sets'), '3-Piece Sets', 'Tiered flared sharara set in rich royal azure Chanderi with mirror work embroidery, paired with a matching zari bordered dupatta.', 6800, NULL, 'Sold Out', TRUE, FALSE, FALSE, FALSE, TRUE, NULL, NULL) on conflict (slug) do update set name=excluded.name, category_id=excluded.category_id, category=excluded.category, description=excluded.description, price_int=excluded.price_int, original_price_int=excluded.original_price_int, availability=excluded.availability, is_new_arrival=excluded.is_new_arrival, is_bestseller=excluded.is_bestseller, is_on_sale=excluded.is_on_sale, is_out_of_stock=excluded.is_out_of_stock, fabric=excluded.fabric, fabric_care=excluded.fabric_care, is_active=TRUE;
delete from public.product_images where product_id=(select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara');
insert into public.product_images (product_id, url, is_primary, display_order) values ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), '/images/products/set_ivory_2.jpg', TRUE, 0), ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), '/images/products/set_ivory_1.jpg', FALSE, 1);
delete from public.product_variants where product_id=(select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara');
insert into public.product_variants (product_id, size_label, is_active) values ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), 'M', TRUE), ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), 'L', TRUE);
delete from public.inventory where product_id=(select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara');
insert into public.inventory (product_id, stock_quantity) select id, 10 from public.products where slug='neelam-azure-chanderi-3-piece-sharara';
delete from public.product_tags where product_id=(select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara');
insert into public.product_tags (product_id, tag) values ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), 'Sharara'), ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), 'Mirror Work'), ((select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), 'Festive');
delete from public.product_collections where product_id=(select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara');
insert into public.product_collections (product_id, collection_id) select (select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), id from public.collections where slug='bestsellers';
delete from public.product_occasions where product_id=(select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara');
insert into public.product_occasions (product_id, occasion_id) select (select id from public.products where slug='neelam-azure-chanderi-3-piece-sharara'), id from public.occasions where slug='festive';

-- ---------- admin allowlist (sign up with this email after running) ----------
insert into public.admin_emails (email) values ('anviclothing22@gmail.com') on conflict do nothing;
